name: 'R CMD check'
description: 'Prepare and check a package'
inputs:
  sourcepkg:
    description: 'File of the source package'
    required: true
  checkargs:
    description: 'Extra args for R CMD check'
    default: --no-manual --no-vignettes
    required: false
outputs:
  binarypkg:
    description: 'Filename of the output binary package'
    value: ${{steps.results.outputs.BINARYPKG}}
  checkstatus:
    description: 'Final status of CMD check'
    value: ${{steps.check.outputs.CHECKSTATUS}}
  distro:
    description: 'Which Linux distro we have'
    value: ${{steps.results.outputs.DISTRO}}

runs:
  using: "composite"
  steps:
    - name: Check package
      id: check
      shell: bash
      run: |
        R CMD check ${{inputs.sourcepkg}} --library=mylib --install=check:install.log ${{inputs.checkargs}} || true
        Rscript "${GITHUB_ACTION_PATH}/../results.R"
      env:
        R_CHECK_ENVIRON: ${{github.action_path}}/../check.Renviron

    - name: Inspect check outputs
      id: results
      shell: bash
      run: |
        echo "DISTRO=$(lsb_release -sc)" >> $GITHUB_OUTPUT
        SOURCEPKG="${{ inputs.sourcepkg }}"
        PKGNAME=$(echo $SOURCEPKG | cut -d '_' -f1)
        for BINARYPKG in *-linux-gnu.tar.gz; do
          echo "Built binary package: $BINARYPKG"
          echo "BINARYPKG=$BINARYPKG" >> $GITHUB_OUTPUT
        done
        find . -regex '.*\.Rout' | while read f; do echo "::group::$f"; echo " ===== $f ====="; tail -n1000 $f; echo "::endgroup::"; done
        find . -regex '.*\.fail' | while read f; do echo "::group::$f"; echo " ===== $f ====="; tail -n1000 $f; echo "::endgroup::"; done

# Fail manually instead of 'exit 1' to avoid annotation: https://stackoverflow.com/a/73532770/318752 
    - name: Set failed conclusion
      if: steps.check.outputs.CHECKSTATUS == 'ERROR' || steps.check.outputs.CHECKSTATUS == 'FAILURE'
      uses: actions/github-script@v7
      with:
        script: core.setFailed()
