name: 'Prepare Linux'
description: 'Prepare Linux'

runs:
  using: "composite"
  steps:
    - name: Prep Linux
      shell: bash
      run: |
        nohup Xvfb :6 -screen 0 1280x1024x24 > /tmp/X.log 2>&1 &
        echo "DISPLAY=:6" >> $GITHUB_ENV
        echo "LANG=en_US.UTF-8" >> $GITHUB_ENV
        echo "UserNM=nm --quiet" >> $GITHUB_ENV

# Needed for e.g. 'GRaNIE'
    - name: Free extra disk space for BioConductor
      if: ${{ github.repository == 'r-universe/bioc' || github.repository == 'r-universe/bioc-release' }}
      shell: bash
      run: rm -Rf /host/usr/share/dotnet /host/usr/local/lib/android

    - name: Get source package
      uses: actions/download-artifact@v7
      with:
        name: package-source
        path: .
