name: 'Prepare Windows'
description: 'Prepare Windows'
inputs:
  java:
    description: 'Package depends on rJava'
    required: false
  jags:
    description: 'Package depends on JAGS'
    required: false
  quarto:
    description: 'Package depends on Quarto'
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Rtools on ARM64
      run: |
        if ($null -eq $env:RTOOLS45_AARCH64_HOME) {
          curl -o rtools45.exe -L https://github.com/r-windows/rtools-chocolatey/releases/download/6768/rtools45-aarch64-6768-6492.exe
          Start-Process "rtools45.exe" -argumentlist "/VERYSILENT /SUPPRESSMSGBOXES" -wait
          Remove-Item rtools45.exe
        }
        "R_PLATFORM_PKGTYPE=windows.binary.clang-aarch64" >> $env:GITHUB_ENV
      shell: pwsh
      if: runner.arch == 'arm64'

    - name: Normalize Rtools
      run: |
        if [ "$RTOOLS46_HOME" ]; then
          echo "Found preinstalled toolchain in $RTOOLS46_HOME"
          echo "RTOOLS45_HOME=$RTOOLS46_HOME" >> $GITHUB_ENV
          echo "RTOOLS44_HOME=$RTOOLS46_HOME" >> $GITHUB_ENV
        elif [ "$RTOOLS45_HOME" ]; then
          echo "Found preinstalled toolchain in $RTOOLS45_HOME"
          echo "RTOOLS46_HOME=$RTOOLS45_HOME" >> $GITHUB_ENV
          echo "RTOOLS44_HOME=$RTOOLS45_HOME" >> $GITHUB_ENV
        fi
        if [ "$UNIVERSE_NAME" = "cran" ] || [ "$UNIVERSE_NAME" = "bioc" ]; then
          echo "_R_INSTALL_TIME_PATCHES_=https://www.r-project.org/nosvn/winutf8/ucrt3/" >> $GITHUB_ENV
        fi
      shell: bash
      if: runner.arch != 'arm64'

    - name: "Install JAGS if needed"
      run: |
        curl -o JAGS.exe -L https://github.com/r-universe-org/actions/releases/download/JAGS-4.3.1/JAGS-4.3.1.exe
        Start-Process "JAGS.exe" -argumentlist "/S" -wait
        Remove-Item JAGS.exe
      shell: pwsh
      if: inputs.jags

    - name: "Install Pandoc"
      run: |
        curl -sSLo pandoc.zip -sSL https://github.com/jgm/pandoc/releases/download/3.9/pandoc-3.9-windows-x86_64.zip
        unzip pandoc.zip
        cp -vf "pandoc-3.9/pandoc.exe" "/c/windows/"
        rm -Rf pandoc*
      shell: bash
      continue-on-error: true

    - name: "Install Quarto"
      run: choco install -y --no-progress quarto
      shell: pwsh
      if: inputs.quarto
      continue-on-error: true

    - name: Get source package
      uses: actions/download-artifact@v7
      with:
        name: package-source
        path: .

# Adds a preinstalled (cached) python version to the path
    - name: Set python version
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
