inputs:
  name:
    required: true
  JOB_STATUS: 
    description: 'Build success status'
  DISTRO: 
    description: 'Name of operating system'
  FILE: 
    description: 'Filename to upload'
  TARGET: 
    description: 'One of source, win, mac, wasm'
  CHECKSTATUS:
    description: 'Output status of CMD-check'

runs:
  using: "composite"
  steps: 
    - shell: bash
      run: |
        echo "JOB_STATUS='${{ inputs.JOB_STATUS }}'" > pkgdata.txt
        echo "DISTRO='${{ inputs.DISTRO }}'" >> pkgdata.txt
        echo "FILE='${{ inputs.FILE }}'" >> pkgdata.txt
        echo "TARGET='${{ inputs.TARGET }}'" >> pkgdata.txt
        echo "CHECKSTATUS='${{ inputs.CHECKSTATUS }}'" >> pkgdata.txt
        echo "STOREDATE=$(date '+%Y%m%d')" >> pkgdata.txt

    - shell: bash
      run: |
        if [ -n "$(find "${{ inputs.FILE }}" -prune -size +100M)" ]; then
          echo "File ${{ inputs.FILE }} is larger than 100 MB. This is not allowed"
          exit 1
        fi

    - name: "Save source package"
      uses: actions/upload-artifact@v4
      with:
        name:  ${{ inputs.name }}
        path: |
          ${{ inputs.FILE }}
          pkgdata.txt
          checkresults.*
