name: 'Build package'
description: 'Prepare and build package'
inputs:
  sourcepkg:
    description: 'File of the source package'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install package dependencies
      run: |
        Rscript "${GITHUB_ACTION_PATH}/../getdeps.R" "${{inputs.sourcepkg}}"
        mkdir -p mylib
      shell: bash
      env:
        R_ENVIRON_USER: ${{github.action_path}}/../check.Renviron
        R_PROFILE_USER: ${{github.action_path}}/../Rprofile

    - name: Build the package
      shell: bash
      run: R CMD INSTALL ${{inputs.sourcepkg}} --library=mylib --build 2>&1 | tee install.log
      env:
        MACOSX_DEPLOYMENT_TARGET: "11.0"
        R_ENVIRON_USER: ${{github.action_path}}/../check.Renviron
