name: 'Build package'
description: 'Prepare and build package'
inputs:
  sourcepkg:
    description: 'File of the source package'
    required: true

runs:
  using: "composite"
  steps:
    - name: Build the package
      shell: bash
      run: R CMD INSTALL ${{inputs.sourcepkg}} --library=mylib --build 2>&1 | tee install.log
      env:
        MACOSX_DEPLOYMENT_TARGET: "11.0"
        R_ENVIRON_USER: ${{github.action_path}}/../check.Renviron
# SDKROOT is set in 'prepare' step now
#       SDKROOT: /Applications/Xcode_16.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
