name: 'Deploy packages'
description: 'Deploy all the packages'
outputs:
  jobdata:
    description: 'JSON blob with jobs data'
    value: ${{steps.jobsdata.outputs.jobdata}}
  version_change:
    description: 'If the version number was changed'
    value: ${{steps.version.outputs.version_change}}

runs:
  using: "composite"
  steps:
    - name: Get jobs results
      id: jobsdata
      shell: bash
      run: ${GITHUB_ACTION_PATH}/jobsdata.sh
    - name: Check for changed version number
      id: version
      shell: bash
      run: ${GITHUB_ACTION_PATH}/version.sh
    - name: Deploy
      id: deploy
      shell: bash
      run: ${GITHUB_ACTION_PATH}/action.sh
