name: 'R CMD check'
description: 'Prepare and check a package'
inputs:
  sourcepkg:
    description: 'File of the source package'
    required: true
  checkargs:
    description: 'Extra args for R CMD check'
#    default: --no-manual --no-build-vignettes # knitr has a bug for --no-build-vignettes
    default: --no-manual --no-vignettes
    required: true
  java:
    description: 'Package depends on rJava'
    required: false
  jags:
    description: 'Package depends on JAGS'
    required: false

outputs:
  binarypkg:
    description: 'Filename of the output binary package'
    value: ${{steps.results.outputs.binarypkg}}
  checkstatus:
    description: 'Final status of CMD check'
    value: ${{steps.conclude.outputs.CHECKSTATUS}}
  hasplatform:
    description: 'The build is only for one architecture'
    value: ${{steps.results.outputs.hasplatform}}

runs:
  using: "composite"
  steps:
    - name: Install package dependencies
      run: Rscript "${GITHUB_ACTION_PATH}/../getdeps.R" "${{inputs.sourcepkg}}"
      shell: bash
      env:
        R_ENVIRON_USER: ${{github.action_path}}/../check.Renviron
        R_PROFILE_USER: ${{github.action_path}}/../Rprofile
#        R_COMPILE_AND_INSTALL_PACKAGES: never
    - name: Build and check package
      shell: bash
      run: R CMD check ${{inputs.sourcepkg}} --install-args="--build" ${{inputs.checkargs}}
      env:
        MACOSX_DEPLOYMENT_TARGET: 11.0
#        SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk
        R_CHECK_ENVIRON: ${{github.action_path}}/../check.Renviron
        R_PROFILE_USER: ${{github.action_path}}/../Rprofile

    - name: Parse CMD check results
      if: always()
      id: conclude
      run: Rscript "${GITHUB_ACTION_PATH}/../results.R"
      shell: bash

    - name: Inspect check outputs
      if: always()
      id: results
      shell: bash
      run: |
        SOURCEPKG="${{ inputs.sourcepkg }}"
        BINARYPKG="${SOURCEPKG%tar.gz}tgz"
        PKGNAME=$(echo $SOURCEPKG | cut -d '_' -f1)
        if [ -f "${BINARYPKG}" ]; then
          echo "Built binary package: $BINARYPKG"
          echo "binarypkg=$BINARYPKG" >> $GITHUB_OUTPUT
          if tar -xOf "${BINARYPKG}" "${PKGNAME}/DESCRIPTION" | grep -q '^Built.*64'; then
            echo "hasplatform=true" >> $GITHUB_OUTPUT
          fi
        else
          echo "No binary package $BINARYPKG found. Skipping deployment."
        fi
        find . -regex '.*\.R*out' | while read f; do echo "::group::$f"; echo " ===== $f ====="; tail -n1000 $f; echo "::endgroup::"; done
        find . -regex '.*\.fail' | while read f; do echo "::group::$f"; echo " ===== $f ====="; tail -n1000 $f; echo "::endgroup::"; done
