name: 'Prepare MacOS system'
description: 'Prepare system for building R packages'
inputs:
  version:
    description: 'Version of R'
    required: true
  fortran:
    description: 'Package uses Fortran'
    required: false
  golang:
    description: 'Package uses Go'
    required: false
  jags:
    description: 'Package depends on JAGS'
    required: false
  quarto:
    description: 'Package depends on Quarto'
    required: false

runs:
  using: "composite"
  steps:

    - shell: bash
      run: |
        sudo mkdir -p /opt
        sudo chown $USER /opt
        echo "ARCH=$(uname -m)" >> $GITHUB_ENV

    - name: Cache tools
      uses: actions/cache@v4
      with:
        path: |
          /opt/X11
          /opt/gfortran
          /opt/R/x86_64
          /opt/R/arm64
        key: ${{ runner.os }}-${{ inputs.version }}-25

    - shell: bash
      run: |
        echo "::group::Removing Homebrew"
        cp $(which gtar git-lfs rustup-init) .
        brew unlink $(brew list --formula) || true
        brewdir=$(brew --repo)
        sudo mv $(brew --prefix)/Cellar $(brew --prefix)/Cellar.old
        sudo rm -vf $(which brew)
        sudo mv $brewdir $brewdir.old
        cp -f gtar git-lfs rustup-init /usr/local/bin/
        hash -r
        echo "Done removing homebrew!"
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        ln -sf /usr/local/bin/rustup-init $HOME/.cargo/bin/rustup
        cargo --version
        echo "::endgroup::"

    - shell: bash
      run: |
        if [ -d "/opt/X11/lib" ]; then
          echo "/opt/X11/lib exists. Skipping xQuartz installation"
        else
          echo "::group::Installing XQuartz"
          echo "Downloading XQuartz..."
          curl --retry 3 -fLO https://github.com/XQuartz/XQuartz/releases/download/XQuartz-2.8.5/XQuartz-2.8.5.pkg
          sudo installer -pkg "XQuartz-2.8.5.pkg" -target /
          rm -f XQuartz-2.8.5.pkg
          echo "Done installing XQuartz!"
          echo "::endgroup::"
        fi

    - shell: bash
      run: |
        if [ "${{inputs.version}}" = "devel" ]; then
          installer="https://github.com/R-macos/gcc-14-branch/releases/download/gcc-14.2-darwin-r2.1/gfortran-14.2-universal.pkg"
          makevars="${{github.action_path}}/gfortran-14/Makevars-$ARCH"
        else 
          installer="https://github.com/R-macos/gcc-12-branch/releases/download/12.2-darwin-r0.1/gfortran-12.2-universal.pkg"
          makevars="${{github.action_path}}/gfortran-12/Makevars-$ARCH"
        fi
        if [ -d "/opt/gfortran/bin" ]; then
          echo "/opt/gfortran/bin exists. Skipping fortran installation"
        else
          echo "::group::Installing Fortran"
          echo "Downloading Fortran..."
          curl --retry 3 -fsSL $installer -o gfortran.pkg
          sudo installer -pkg "gfortran.pkg" -target /
          rm -f gfortran.pkg
          echo "Done installing Fortran!"
          echo "::endgroup::"
        fi
        mkdir -p ~/.R
        cp -f $makevars ~/.R/Makevars
        echo "/opt/gfortran/bin" >> $GITHUB_PATH

    - shell: bash
      run: |
        echo "::group::Installing CRAN libs bundle"
        CRANPATH="/opt/R/$ARCH"
        if [ -f "$CRANPATH/bin/pkg-config" ]; then
          echo "$CRANPATH/bin/pkg-config exists, skipping download"
        else
          curl --retry 3 -fsSL https://github.com/r-universe-org/macos-libs/releases/download/2025-03-02/cranlibs-everything.tar.xz -o libs.tar.xz
          sudo tar -xf libs.tar.xz -C / opt
          rm -f libs.tar.xz
        fi
        PATH="$CRANPATH/bin:$PATH"
        echo "$CRANPATH/bin" >> $GITHUB_PATH
        export PKG_CONFIG_PATH="$CRANPATH/lib/pkgconfig:$CRANPATH/share/pkgconfig:/usr/lib/pkgconfig:/opt/X11/lib/pkgconfig:/opt/X11/share/pkgconfig"
        echo "PKG_CONFIG_PATH=${PKG_CONFIG_PATH}" >> $GITHUB_ENV
        echo "PROJ_LIB=$CRANPATH/share/proj" >> $GITHUB_ENV
        echo "PROJ_GDAL_DATA_COPY=TRUE" >> $GITHUB_ENV
        echo "Available libs through pkg-config:"
        pkg-config --list-all
        echo "Done installing CRAN bundle!"
        echo "::endgroup::"

    - shell: bash
      if: inputs.quarto
      run: |
        if quarto --version 2>/dev/null; then
          echo "Skipping quarto installation"
        else
          echo "::group::Installing Quarto"
          pkgfile="quarto-1.6.39-macos.pkg"
          curl --retry 3 -fOL https://github.com/quarto-dev/quarto-cli/releases/download/v1.6.39/$pkgfile
          sudo installer -pkg $pkgfile -target /
          rm -f $pkgfile
          echo "::endgroup::"
        fi

    - shell: bash
      run: |
        if pandoc --version 2>/dev/null; then
          echo "Skipping pandoc installation"
        else
          echo "::group::Installing Pandoc"
          pkgfile="pandoc-3.3-$ARCH-macOS.pkg"
          curl --retry 3 -fOL https://github.com/jgm/pandoc/releases/download/3.3/$pkgfile
          sudo installer -pkg $pkgfile -target /
          rm -f $pkgfile
          cp -f /usr/local/bin/pandoc /opt/R/$ARCH/bin/  #Copy to cache
          echo "::endgroup::"
        fi

    - name: "Install JAGS if needed"
      shell: bash
      run: |
        echo "::group::Installing JAGS"
        curl --retry 3 -fLO https://github.com/autobrew/bundler/releases/download/jags-4.3.2/JAGS-4.3.2.pkg
        sudo installer -pkg JAGS-4.3.2.pkg -target /
        rm -f JAGS-4.3.2.pkg
        if [ -d "/opt/R/arm64/lib/pkgconfig" ]; then
          cp -f /usr/local/lib/pkgconfig/jags.pc /opt/R/arm64/lib/pkgconfig/
        fi
        echo "Done installing JAGS!"
        echo "::endgroup::"
      if: inputs.jags

    - name: "Install GO if needed"
      shell: bash
      run: |
        if go version 2>/dev/null; then
          echo "Skipping GO installation"
        else
          echo "::group::Installing GO"
          if [ "$ARCH" = "arm64" ]; then
          installgo="go1.24.0.darwin-arm64.pkg"
          else
          installgo="go1.24.0.darwin-amd64.pkg"
          fi
          curl --retry 3 -fLOSs https://go.dev/dl/$installgo
          sudo installer -pkg $installgo -target /
          rm -f $installgo
          echo "Done installing GO!"
          echo "::endgroup::"
        fi
        echo "/usr/local/go/bin" >> $GITHUB_PATH
      if: inputs.golang
