name: 'Build package'
description: 'Prepare and build package'
inputs:
  sourcepkg:
    description: 'File of the source package'
    required: true

runs:
  using: "composite"
  steps:
      ## NOTE: ${{github.action_path}} does not work within container script, we need $GITHUB_ACTION_PATH
    - name: Install package dependencies
      run: |
        Rscript "${GITHUB_ACTION_PATH}/../getdeps.R" "${{inputs.sourcepkg}}"
        mkdir -p mylib
      shell: bash
      env:
        R_ENVIRON_USER: ${{github.action_path}}/../check.Renviron

    - name: Build the package
      shell: bash
      run: R CMD INSTALL ${{inputs.sourcepkg}} --library=mylib --build 2>&1 | tee install.log
      env:
        R_ENVIRON_USER: ${{github.action_path}}/../check.Renviron
