name: 'Get package dependencies'
description: 'Install native package and dependencies'
inputs:
  sourcepkg:
    description: 'File of the source package'
    required: true
outputs:
  rversion:
    description: 'Version of R'
    value: ${{steps.getdeps.outputs.rversion}}

runs:
  using: "composite"
  steps:
    - id: getdeps
      name: Install native package and dependencies
      run: |
        dir.create("mylib")
        cat(paste0('rversion=', getRversion(), '\n'), file = Sys.getenv("GITHUB_OUTPUT"), append = TRUE)
        pak::pak('deps::./${{inputs.sourcepkg}}')
      shell: Rscript {0}
      env:
        R_ENVIRON_USER: ${{github.action_path}}/../check.Renviron
